-- require('nightfox').setup({
--   options = {
--     styles = {
--       -- comments = "italic",
--       keywords = "bold",
--       types = "bold",
--     }
--   }
-- })

-- vim.cmd("colorscheme duskfox")
